
# The CLI picks up the token from the SENTRY_AUTH_TOKEN environment variable (set via your .env files).
# Learn more at https://docs.sentry.io/product/cli/configuration/
defaults.org=chores-nest
defaults.project=chores-nest

defaults.url=https://sentry.io/
