#Sentry config for release builds
#Tue Jul 07 10:46:48 IST 2026
defaults.org=chores-nest
auth.token=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
defaults.project=chores-nest
defaults.url=https\://sentry.io/
