# CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

# Resolve react_native_pods.rb with node to allow for hoisting
# A helper so we can use scripts bundled within node_modules.
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Ensure the RN pods helper and permissions setup script are loaded.
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

ENV['NODE_BINARY'] = '/opt/homebrew/bin/node'

platform :ios, min_ios_version_supported
use_modular_headers!
prepare_react_native_project!
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ChoresNest' do
  config = use_native_modules!
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson', modular_headers: true
  pod 'FirebaseAnalytics', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'Sentry', :modular_headers => true

  setup_permissions([
    'Camera',
    'Microphone',
    'PhotoLibrary',
    'PhotoLibraryAddOnly',
    'Notifications',
    'MediaLibrary',
  ])

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
