
auth.token=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

defaults.org=chores-nest
defaults.project=react-native

defaults.url=https://sentry.io/
