BEGIN;

ALTER TABLE IF EXISTS public.events REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.tasks REPLICA IDENTITY FULL;

-- Rollback (if needed):
-- ALTER TABLE public.events REPLICA IDENTITY DEFAULT;
-- ALTER TABLE public.tasks REPLICA IDENTITY DEFAULT;

COMMIT;

BEGIN;

ALTER TABLE IF EXISTS public.events REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.tasks REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.lists REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.list_items REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.list_categories REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.members REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.recipes REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.collections REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.collection_recipes REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.meal_plans REPLICA IDENTITY FULL;

COMMIT;
