BEGIN;

ALTER TABLE IF EXISTS public.events REPLICA IDENTITY FULL;
ALTER TABLE IF EXISTS public.tasks REPLICA IDENTITY FULL;

-- Rollback (if needed):
-- ALTER TABLE public.events REPLICA IDENTITY DEFAULT;
-- ALTER TABLE public.tasks REPLICA IDENTITY DEFAULT;

COMMIT;

